//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasProjectPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerTasks
    {
        public int ID { get; set; }
        public int ID_Task { get; set; }
        public int ID_User { get; set; }
        public string Text { get; set; }
        public string File { get; set; }
        public string DateCompletion { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
