//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasProjectPlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksGroups
    {
        public int ID { get; set; }
        public int ID_Tasks { get; set; }
        public int ID_Group { get; set; }
    
        public virtual GroupsStudents GroupsStudents { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
